"""Cars & Users

Revision ID: 5b8fe7f06236
Revises: fbbc254ec1e5
Create Date: 2021-04-16 13:15:02.741870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8fe7f06236'
down_revision = 'fbbc254ec1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maker', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('manufacture_year', sa.String(length=1000), nullable=True),
    sa.Column('engine_displacement', sa.String(length=1000), nullable=True),
    sa.Column('engine_power', sa.Integer(), nullable=True),
    sa.Column('color_slug', sa.String(length=50), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=True),
    sa.Column('door_count', sa.Integer(), nullable=True),
    sa.Column('seat_count', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=1000), nullable=True),
    sa.Column('price_eur', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
